[tool.pylint.MASTER]
disable = [
	"missing-docstring",
	"relative-beyond-top-level",
]
ignored-modules = [
	"sublime",
	"sublime_plugin",
]
ignore-paths = [
	"sshubl/vendor",
]
jobs = 0
load-plugins = [
	"pylint_secure_coding_standard",
]
py-version = "3.8"

[tool.pylint.DESIGN]
min-public-methods = 0

[tool.mypy]
check_untyped_defs = true
exclude = [
	"sshubl/vendor",
]
python_version = "3.8"

[[tool.mypy.overrides]]
module = "sublime.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "sublime_plugin.*"
ignore_missing_imports = true

[tool.ruff]
line-length = 100
exclude = [
	"sshubl/vendor",
]
target-version = "py38"
